"""empty message

Revision ID: 519295707349
Revises: b0cf32cf5f53
Create Date: 2024-10-02 04:00:07.125493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519295707349'
down_revision = 'b0cf32cf5f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_centers_courses',
    sa.Column('training_center_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['training_center_id'], ['training_centers.id'], ),
    sa.PrimaryKeyConstraint('training_center_id', 'course_id')
    )
    op.drop_table('Training Centers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Training Centers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('img', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='Training Centers_course_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Training Centers_pkey')
    )
    op.drop_table('training_centers_courses')
    op.drop_table('training_centers')
    # ### end Alembic commands ###
