"""empty message

Revision ID: 5d0886f0329c
Revises: ea82962bc991
Create Date: 2024-10-02 03:27:02.639819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0886f0329c'
down_revision = 'ea82962bc991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Training Centers', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Training Centers', 'location',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Training Centers', 'img',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('Training Centers', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Training Centers', 'address',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Training Centers', 'img',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('Training Centers', 'location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('Training Centers', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
