"""empty message

Revision ID: 822e24a7620c
Revises: 
Create Date: 2024-10-01 15:45:50.701341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822e24a7620c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('rating', sa.String(length=50)))
    op.add_column('courses', sa.Column('princing', sa.String(length=50)))
    op.add_column('courses', sa.Column('startingdate', sa.String(length=50)))
    op.add_column('courses', sa.Column('enddate', sa.String(length=50)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'enddate')
    op.drop_column('courses', 'startingdate')
    op.drop_column('courses', 'princing')
    op.drop_column('courses', 'rating')
    # ### end Alembic commands ###
