"""empty message

Revision ID: b0cf32cf5f53
Revises: 5d0886f0329c
Create Date: 2024-10-02 03:34:05.545194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cf32cf5f53'
down_revision = '5d0886f0329c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('pricing', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('requirements', sa.String(length=255), nullable=True))
    op.alter_column('courses', 'brief',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('courses', 'img',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('courses', 'criteria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('courses', 'content',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('courses', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('courses', 'Requirements')
    op.drop_column('courses', 'princing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('princing', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('Requirements', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('courses', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('courses', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('courses', 'criteria',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('courses', 'img',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('courses', 'brief',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('courses', 'requirements')
    op.drop_column('courses', 'pricing')
    # ### end Alembic commands ###
