"""empty message

Revision ID: bcf8e030c0ef
Revises: 3ee09780d0b7
Create Date: 2024-10-14 13:50:24.812451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf8e030c0ef'
down_revision = '3ee09780d0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_form', sa.Column('employment_status', sa.String(length=255), nullable=True))
    op.drop_column('apply_form', 'employment_states')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_form', sa.Column('employment_states', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('apply_form', 'employment_status')
    # ### end Alembic commands ###
