"""empty message

Revision ID: ea82962bc991
Revises: 822e24a7620c
Create Date: 2024-10-02 03:22:26.738427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea82962bc991'
down_revision = '822e24a7620c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Training Centers',
    sa.Column('id', sa.Integer()),
    sa.Column('course_id', sa.Integer()),
    sa.Column('title', sa.String(length=100)),
    sa.Column('location', sa.String(length=32)),
    sa.Column('img', sa.String(length=32)),
    sa.Column('address', sa.Text()),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('courses', sa.Column('brief', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('img', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('Requirements', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('criteria', sa.String(length=50), nullable=True))
    op.add_column('courses', sa.Column('content', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'content')
    op.drop_column('courses', 'criteria')
    op.drop_column('courses', 'Requirements')
    op.drop_column('courses', 'img')
    op.drop_column('courses', 'brief')
    op.drop_table('Training Centers')
    # ### end Alembic commands ###
